### ISSUE TITLE
Expose a way to compile mdast to html

### ISSUE THREAD

**Issue by maplant** [wooorm/markdown-rs#102]
As far as I can tell, there's no way to compile mdast once you have parsed a string to it.
This would be useful because I want to modify a mdast tree and then compile it to HTML

**Comment by ChristianMurphy** [comment]
Welcome @maplant! 👋 
This is duplicate of https://github.com/wooorm/markdown-rs/issues/101 and https://github.com/wooorm/markdown-rs/issues/32
Please check the issue tracker before logging a new ticket, thanks!
