### ISSUE TITLE
HTML in markdown

### ISSUE THREAD

**Issue by uberFoo** [wooorm/markdown-rs#112]
This crate quotes embedded HTML rather than passing it through, as the CommonMark crate suggests.

Am I missing an option or something?

Thanks for the help!

**Comment by ChristianMurphy** [comment]
Welcome @uberFoo! 👋 
Sorry you ran into some confusion.

The crate does not quote the HTML, it does escape it and prevent it from opening your app up to XSS by default.
https://github.com/wooorm/markdown-rs?tab=readme-ov-file#security

This can be configured with the options noted in the readme, if you trust the content being pass through.

**Comment by uberFoo** [comment]
Super — I must have missed that. Thank you!
