### ISSUE TITLE
Prevent lettered list ?

### ISSUE THREAD

**Issue by haheute** [wooorm/markdown-rs#117]
Is there a way to prevent the generation of a lettered list when a sentence starts with a letter and a dot?
I want to write this:

```
.. bleibt, bis ein Mord seinem Schicksal eine neue Wende gibt.

A. Bogdanows utopischer Roman "Der rote Planet"..
```

That creates a list like:
A.
B.

I can escape it with a backslash: `A\. Bogdanow` but then the backslash is visible in the result..

**Comment by wooorm** [comment]
My Germanic friend, I don't think what you say is correct. You're probably not on the currently maintained version of this crate: use the alpha version.
Markdown doesn't support alphabetic lists. So we don't support them at all

**Comment by haheute** [comment]
Indeed... with `1.0.0-alpha.17` it is okay...
I was using the `v0.3.0` version, because I thought, "latest stable"... anyway..
thanks!

**Comment by haheute** [comment]
forgot to close... merci.
