### ISSUE TITLE
Add support for nested fenced code blocks

### ISSUE THREAD

**Issue by nokome** [wooorm/markdown-rs#119]
First, thanks for this crate! (and more generally all the awesome work you do to help developers parse Markdown! 🙌🏽 )

In my usage, I need to handle nested fenced code blocks, but as the follow test shows, this is currently not supported. If you think this would be a good thing to support let me know and I can have a go at a PR.

`````rust
use common_dev::pretty_assertions::assert_eq;
use markdown::{
    mdast::{Code, Node},
    to_mdast, ParseOptions,
};

#[test]
fn nested_code_block() {
    let options = ParseOptions::gfm();

    let mdast = to_mdast(
        r#"
```md

First code block

````python
# Nested code block
````

```
"#,
        &options,
    )
    .unwrap();

    match mdast.children().unwrap().first().unwrap() {
        Node::Code(Code { lang, value, .. }) => {
            assert_eq!(lang.as_deref(), Some("md"));
            // This currently passes but it shouldn't: the python code block is truncated
            assert_eq!(
                value,
                "
First code block

````python
# Nested code block"
            );
        }
        _ => assert!(false, "unexpected node type"),
    }
}
`````

**Comment by ChristianMurphy** [comment]
Welcome @nokome! 👋 
It is supported, the syntax is different from what you are trying.
It needs to have a descending number of backticks.
Larger on the outside smaller on the inside.

`````md
````md

First code block

```python
# Nested code block
```

````
`````

**Comment by nokome** [comment]
Thanks @ChristianMurphy for the quick response! That syntax is a little more awkward to implement for my use case but great to know it is supported. Feel free to close this.

**Comment by ChristianMurphy** [comment]
I assume your use case is wanting to use markdown.
The markdown crate, follows the markdown standard https://commonmark.org/
Descending number of backticks is how nesting code works in markdown.

If your use case includes making yet another markdown flavor, see https://github.com/wooorm/markdown-rs/issues/32 for work toward plugins and syntax extensions.

**Comment by wooorm** [comment]
Sticking with standards (in this case, CommonMark/GFM), means that your markdown files will work everywhere. Here on GH too. And in the syntax highlighter in your editor.
Going with a non-standard format would mean the content is not so portable!
