### ISSUE TITLE
Q: support for auto-coloring Rust code?

### ISSUE THREAD

**Issue by amab8901** [wooorm/markdown-rs#125]
Does this crate support markdown syntax for adding colors to Rust code like below (i.e. color consistently and automatically informing you whether it's a struct, or function, or enum, or keyword, etc)?

``` rust
struct Struct {
    field1: String,
}
```

**Comment by wooorm** [comment]
I have no clue what you are asking. Please use more words and examples.

**Comment by amab8901** [comment]
If I write like this in Markdown:

![image](https://github.com/user-attachments/assets/c806c2fa-ae29-4ab9-8d8c-ee4fbf6a4d59)

... then Markdown will parse it like this:

![image](https://github.com/user-attachments/assets/35df0c87-b015-4d2a-a999-f8cae4c7d4ee)

Does this crate have this feature?

**Comment by wooorm** [comment]
That's not what markdown does. That's what GH and similar things do. It's called "syntax highlighting". Markdown turns that word, "rust", into a class. That's what we do here too. You can then use that class, with JavaScript for example, to do syntax highlighting yourself.
