### ISSUE TITLE
Installing as a binary

### ISSUE THREAD

**Issue by ElSandman** [wooorm/markdown-rs#126]
I noticed there isn't anything about installing as a binary in the README, but when I run `cargo install markdown` it installs. The issue is that there's no help menu, and when I pass a non-existent file it just panics. I'm unsure if this is intentinal. I also saw in the README that it said

> 👉 Note: this is a new crate that reuses an old name. The old crate (0.3.0 and lower) has a bunch of problems. Make sure to use the new crate, currently in alpha at 1.0.0-alpha.20.

I assume this applies to `cargo install` too. which doesn't have a `@1.0.0-alpha.20` version. I guess I'm mainly asking if this is intentional or if there's an issue or some other way to install it.

If it is intentional could you yank it (I'm unfamiliar with the crates.io registry, so I don't really know if you can yank specifically the binary or not)

**Comment by wooorm** [comment]
> cargo install markdown

You are getting the old markdown. In the readme, it is said that you should append `@1.0.0-alpha.20` to get the new version.

> which doesn't have a `@1.0.0-alpha.20` version.

I don’t understand, cargo says it exists? https://crates.io/crates/markdown/1.0.0-alpha.20

---

This (new, much improved) project does not provide a binary. I think that’s what you are asking. For a CLI?
It’s intentional that that doesn’t exist.
Others can wrap this project into a CLI to do that!

**Comment by ElSandman** [comment]
Yes, I was asking if there was a CLI. Thank you for clarifying. I just found it kind of wierd that I could `cargo install` it even though it wasn't mean't to be. Very confusing. So, I'm not very familiar with how crates.io works, but is it possible to yank just the binary and not the library, so you'll get a message when installing it, or atleast note the wierdness in the README?

**Comment by wooorm** [comment]
>  I just found it kind of wierd that I could cargo install it even though it wasn't meant to be. Very confusing.

Cargo isn‘t only for CLIs, I think that’s where the confusion stems from. It’s also for packages like this, that only have an API
