### ISSUE TITLE
Windows absolute image paths not working

### ISSUE THREAD

**Issue by tdaron** [wooorm/markdown-rs#130]
Hi ! 

With this simple markdown example:

```markdown
![](C:\toto.png)
```

Because of the "C:\\" the generated HTML is:

```html
<img src="" alt="" />
```

With nothing inside the src. Am i doing something wrong here ?

**Comment by wooorm** [comment]
Hey!

a) paths to your own computer probably don’t work
b) `allow_dangerous_protocol`: https://docs.rs/markdown/1.0.0-alpha.20/markdown/struct.CompileOptions.html#structfield.allow_dangerous_protocol
