### ISSUE TITLE
Links with urls containing spaces not parsed as links

### ISSUE THREAD

**Issue by christofferaakre** [wooorm/markdown-rs#151]
As far as I can tell, links of the form [Link Text](link-value) are parsed as 
```
Link { children: [Text { value: "Link text", position: Some(2:14-2:23 (23-32)) }], position: Some(2:13-2:36 (22-45)), url: "link-value", title: None }
```

but links of the form [Link Text](Link Value) are parsed as
```
Text { value: "hello world [Link text](Link Value)", position: Some(2:1-2:36 (10-45)) }], position: Some(2:1-2:36 (10-45)) }
```

The entire file I am parsing here is
```
# Header
hello world [Link text](Link Value)
```

and switching the url value between "Link Value" and "link-value".

Is this intended behaviour, that spaces are not supported in urls? Or should this be fixed? It would be nice for my usecase as I would like to write a wiki in markdown and use this to parse that markdown, and it would be nice to be able to have filenames with spaces for that.

**Comment by ChristianMurphy** [comment]
Welcome @christofferaakre! 👋 

> Is this intended behaviour, that spaces are not supported in urls? 

It is expected, links need to be url encoded to work. https://spec.commonmark.org/0.31.2/#example-502

Example of how your example runs in the commonmark reference implementation
https://spec.commonmark.org/dingus/?text=%23%20Header%0Ahello%20world%20%5BLink%20text%5D(Link%20Value)

and same behavior on GitHub itself

---

# Header
hello world [Link text](Link Value)

---


What you likely want is

```md
# Header
hello world [Link text](Link%20Value)
```

which renders as:

# Header
hello world [Link text](Link%20Value)

**Comment by christofferaakre** [comment]
Thank you for the quick answer! Yes, what you suggested is indeed exactly what I want. Sorry for taking up your time. Have a nice rest of your day!
