### ISSUE TITLE
Feature Request: Add tag for release `0.3.0`

### ISSUE THREAD

**Issue by freeform-andre** [wooorm/markdown-rs#157]
Hi, thanks for this crate!

I was wondering if any maintainers would be willing to tag the commit used for at least https://crates.io/crates/markdown/0.3.0 but potentially older releases as well. That'd be helpful in triaging issues.

**Comment by freeform-andre** [comment]
@wooorm do you know when the next release will be? I found this crate on `crates.io` and followed the seemingly standard practice of adding a crate. Is `0.3.0` not a commit in this repo?

**Comment by ChristianMurphy** [comment]
> Is 0.3.0 not a commit in this repo?

It is not

**Comment by ChristianMurphy** [comment]
See the intro in the readme

> Note: this is a new crate that reuses an old name. The old crate (0.3.0 and lower) has a bunch of problems. Make sure to use the new crate, currently in alpha at 1.0.0-alpha.21.
