### ISSUE TITLE
Escaped Tags

### ISSUE THREAD

**Issue by Pspritechologist** [wooorm/markdown-rs#158]
The `to_html_with_options` function seems to be escaping a couple random tags out of embedded HTML, even with `allow_dangerous_html` set to true.
Specifically it's escaping the opening brace of my `script` and `title` tags. Any idea why this might be or how to prevent it?

**Comment by mark-addams001881** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modify the gfm_tagfilter function to check the allow_dangerous_html flag before applying the tag filter. This will prevent escaping of HTML tags when allow_dangerous_html is set to true.

You can review changes in this commit: https://github.com/mark-addams001881/wooorm-markdown-rs-158/commit/ff4e27309e52450f6e71c4e1688c772be76ad9ff.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by Pspritechologist** [comment]
Turns out GFM was also enabling its own tag filter, I managed to find it and turning it off solved my issue.
