### ISSUE TITLE
tokeniser.rs:738 spamming console

### ISSUE THREAD

**Issue by lasswoj** [wooorm/markdown-rs#41]
Any chance that future wersions wont spam that much? :(
Its hard for me to get my own logs.

**Comment by wooorm** [comment]
You have debugging on. You can turn that off?

**Comment by lasswoj** [comment]
If i understand you correctly--i would rather keep my current log level, and simply not get logs from dependency.
Any chance for that?

**Comment by ChristianMurphy** [comment]
You can configure your logging to do that.
See this discussion for some options on how to set log levels for individual crates https://www.reddit.com/r/rust/comments/85qp50/how_to_disable_logging_for_certain_crates

**Comment by wooorm** [comment]
And `env_logger`s own docs: https://docs.rs/env_logger/latest/env_logger/index.html
