### ISSUE TITLE
panic on input `* `

### ISSUE THREAD

**Issue by makemeunsee** [wooorm/markdown-rs#42]
Hello,

This input `* ` (without the double quotes) causes `markdown::to_html` to panic.

e.g.

```rust
fn main() {
    println!("{}", markdown::to_html("* "));
}
```

Just in case, I've pasted the stacktrace below.

Cheers, let me know if I can provide anything else to help.

> thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/markdown-0.3.0/src/parser/block/unordered_list.rs:84:44
stack backtrace:
   0: rust_begin_unwind
             at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/panicking.rs:65:14
   2: core::panicking::panic_bounds_check
             at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/panicking.rs:150:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/slice/index.rs:259:10
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/slice/index.rs:18:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/alloc/src/vec/mod.rs:2736:9
   6: markdown::parser::block::unordered_list::parse_unordered_list
             at /home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/markdown-0.3.0/src/parser/block/unordered_list.rs:84:44
   7: markdown::parser::block::parse_block
             at /home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/markdown-0.3.0/src/parser/block/mod.rs:71:5
   8: markdown::parser::block::parse_blocks
             at /home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/markdown-0.3.0/src/parser/block/mod.rs:27:15
   9: markdown::parser::parse
             at /home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/markdown-0.3.0/src/parser/mod.rs:43:5
  10: markdown::to_html
             at /home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/markdown-0.3.0/src/lib.rs:29:18
  11: markdown_bug::main
             at ./frontend/examples/markdown_bug.rs:2:20
  12: core::ops::function::FnOnce::call_once
             at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/ops/function.rs:513:5

**Comment by ChristianMurphy** [comment]
@makemeunsee could you share a runnable example of the issue?
I tried the sample code you provided with version `1.0.0-alpha.5` and do not see a panic.

Runnable example https://www.rustexplorer.com/b#%2F*%0A%5Bdependencies%5D%0Amarkdown%20%3D%20%221.0.0-alpha.5%22%0A*%2F%0A%0Ause%20markdown%3B%0A%0Afn%20main()%20%7B%0A%20%20%20%20println!(%22%7B%7D%22%2C%20markdown%3A%3Ato_html(%22*%20%22))%3B%0A%7D

<details>
<summary>source from example</summary>

```rust
/*
[dependencies]
markdown = "1.0.0-alpha.5"
*/

use markdown;

fn main() {
    println!("{}", markdown::to_html("* "));
}
```

</details>

**Comment by wooorm** [comment]
Wrong package. You’re using the old one, that has tons of problems. This is a completely new project with the same name.

**Comment by makemeunsee** [comment]
Oh, my bad! Thanks for pointing it out.

**Comment by makemeunsee** [comment]
Note:

https://crates.io/crates/markdown still advertises `0.3.0` as the latest, indicates it was last released 2 years ago.

The `crates` VS code plugin also points to `0.3.0` as the latest. If you have a way to force these external services, I believe it would help with the project visibility and potential confusion.

**Comment by wooorm** [comment]
There is no force. crates doesn’t show alpha releases by default.

**Comment by wooorm** [comment]
As far as I know, at least! If you know of a way to get around it, I’d love to hear

**Comment by makemeunsee** [comment]
No, I'm not aware of anything of the sort, unfortunately. How close do you think this crate is to not being alpha anymore? Do you have a roadmap for the v1? Curious and potentially happy to help...

**Comment by wooorm** [comment]
I want to switch unist nodes towards traits, so that ToString, children, children_mut, position, etc [here](https://github.com/wooorm/markdown-rs/blob/main/src/mdast.rs) would be traits, which mdast/[hast](https://github.com/wooorm/mdxjs-rs/blob/main/src/hast.rs) implement. That’s the only breaking change (perhaps also GH-40) I’d want to do first!

If you want to work on that, that would be much appreciated!

**Comment by makemeunsee** [comment]
I started having a look and trying to wrap my head around the problem/intent.

Is there already an issue open where to discuss? I found about [this comment of yours](https://github.com/wooorm/markdown-rs/issues/27) but it's just a mention of this plan, not the dedicate channel to discuss it, no?

**Comment by wooorm** [comment]
No, there is no particular issue or dedicated channel. Feel free to open one or discuss here!
