### ISSUE TITLE
Build issue with alpha.6 release - serde attribute and create confusion

### ISSUE THREAD

**Issue by remodietlicher** [wooorm/markdown-rs#44]
Hello! Thanks for sharing this beautiful project. Since the latest release `1.0.0-alpha.6` I get the following error when building my project:

```bash
error: cannot find attribute `serde` in this scope
    --> /home/remo/.cargo/registry/src/github.com-1ecc6299db9ec823/markdown-1.0.0-alpha.6/src/mdast.rs:1299:5
     |
1299 |     serde(tag = "type", rename = "mdxJsxFlowElement")
     |     ^^^^^
     |
     = note: `serde` is in scope, but it is a crate, not an attribute
```

It is easy to reproduce, just create a new project `cargo new test` and add

```toml
[dependencies]
markdown = "=1.0.0-alpha.6"
```

This has been tested with rustc 1.67.0 (fc594f156 2023-01-24) and cargo 1.67.0 (8ecd4f20a 2023-01-10) on Ubuntu 22.04.

**Comment by wooorm** [comment]
@remodietlicher Weird, why does it fail there, and not much earlier in the file?

**Comment by remodietlicher** [comment]
I just pasted the last occurrence here. I get the same error on every call to `serde`.
