### ISSUE TITLE
'json' feature should be called `serde` and `serde-json` should not be a dependency

### ISSUE THREAD

**Issue by barafael** [wooorm/markdown-rs#58]
Hi, thanks for this crate, it's got great potential!

I don't quite understand the `json` feature. The way I think it is done:

The `json` feature enables dependencies for `serde` and `serde-json`. In the code, the serializers/deserializers are derived via serde, if the `json` feature is enabled. The `serde-json` crate is not actually used.

Here is how this could be done better (I tested locally):
The `serde` feature enables a dependency on `serde` with the derive feature, as before. In the code, the serializers/deserializers are derived, as before. The `serde-json` crate appears nowhere.

I think this is the conventional and idiomatic way to do this. Are there things I am overlooking here?

EDIT: renamed, was "'json' feature seems half baked" which is vague and unnecessarily insulting. Sorry :)

**Comment by wooorm** [comment]
Hi!

Feel free to continue baking it :)

See also:
* https://github.com/wooorm/markdown-rs/issues/56
* https://github.com/wooorm/markdown-rs/issues/47
* https://github.com/wooorm/markdown-rs/pull/45
* https://github.com/wooorm/markdown-rs/pull/37

**Comment by wooorm** [comment]
Solved in https://github.com/wooorm/markdown-rs/commit/bbb311979c9e9b7305c855c5b93493d285c6ac7b
