### ISSUE TITLE
mdast with frontmatter

### ISSUE THREAD

**Issue by ahkhanjani** [wooorm/markdown-rs#61]
Is it even possible to use mdast with options? And can we get frontmatter in the syntax tree?

**Comment by wooorm** [comment]
Yes? See the api docs for options

**Comment by ahkhanjani** [comment]
@wooorm Could you please show me where I can find this specific thing? I did in fact search the docs but could not find anything related to frontmatter or extensions in general

**Comment by wooorm** [comment]
- Go to docs: https://docs.rs/markdown/1.0.0-alpha.8/markdown/
- Click function you want, this case `to_mdast`: https://docs.rs/markdown/1.0.0-alpha.8/markdown/fn.to_mdast.html
- Click options: https://docs.rs/markdown/1.0.0-alpha.8/markdown/struct.ParseOptions.html
- Click constructs: https://docs.rs/markdown/1.0.0-alpha.8/markdown/struct.Constructs.html
- See `frontmatter`

**Comment by ahkhanjani** [comment]
Thank you so much
