### ISSUE TITLE
make `MDX` to a extra feature?

### ISSUE THREAD

**Issue by mrxiaozhuox** [wooorm/markdown-rs#66]
I think change `mdx` to a feature is better? because sometime we don't need this part.

**Comment by ChristianMurphy** [comment]
It is already optional and configurable based off extensions https://github.com/wooorm/markdown-rs#extensions
Is there a particular reason you think it should be a cargo feature as well?

**Comment by wooorm** [comment]
Hmm. The same could be said for frontmatter, gfm, math, etc.
They're pretty important to this project.
What is the cost, what is the benefit?

**Comment by mrxiaozhuox** [comment]
I don't think `mdx` is a necessary extension for a markdown parser library, the `default-features` just need include very basic function, and other variants can use `features` to import, that can help developer open according to demand. for example I just need a very basic CommonMark parser, but my binary file will include other useless functions.

**Comment by wooorm** [comment]
MDX is an important reason for this project to exist.

This project doesn’t pull in extra dependencies for MDX, which is the case for serde, which is a feature.

> the default-features just need include very basic function

What “very basic” is, is subjective. I think default features should give useful, reasonable defaults.

> I just need a very basic CommonMark parser, but my binary file will include other useless functions.

Can you then please show proof of your request, what the costs and benefits are?

There are always going to be some functions not getting called.

Why do you not care about frontmatter and math?

**Comment by mrxiaozhuox** [comment]
OK, it's just a little suggestion. up to you :laughing:
