### ISSUE TITLE
Option to only produce tags for explicit markdown

### ISSUE THREAD

**Issue by randomairborne** [wooorm/markdown-rs#85]
Hello! I've been loving using this crate in a project of mine, it's really amazing. I have another segment of my project (translations) that would really benefit from being able to have its markdown only emit new HTML for explicit style... requests? For lack of a better word? I checked [Constructs](https://docs.rs/markdown/1.0.0-alpha.14/markdown/struct.Constructs.html) and it states that paragraphs cannot be turned off, which are what is currently causing trouble for me as it's placed around *everything*.

Thanks for making this library!

**Comment by ChristianMurphy** [comment]
Welcome @randomairborne! 👋 
Thanks for sharing!

This feels like it would be a good fit for a mdast/hast plugin as defined in https://github.com/wooorm/markdown-rs/issues/32

Core `markdown-rs` is focused on CommonMark, GFM, and MDX.
Different markdown outputs and flavors are welcome in the ecosystem (plugins). Core itself aims to stick close to the standard and not have too much bloat of options and alternatives.

**Comment by randomairborne** [comment]
[that was big](https://github.com/speederboard/speederboard/blob/main/src/template/translate.rs#L157)
But I did get it done! I would never have thought of this before- thanks!
