### ISSUE TITLE
to_html_with_options isn't found

### ISSUE THREAD

**Issue by paulfrische** [wooorm/markdown-rs#98]
Hi there, when adding this crate to a fresh cargo project with `cargo add markdown` `markdown::to_html_with_options` is't found. All in all I think the documentation around this is very confusing.

```rust
fn main() {
    let text = include_str!("./index.md");
    markdown::to_html_with_options();
}
```
Error:
```
error[E0425]: cannot find function `to_html_with_options` in crate `markdown`
 --> src/main.rs:3:15
  |
3 |     markdown::to_html_with_options();
  |               ^^^^^^^^^^^^^^^^^^^^ not found in `markdown`

For more information about this error, try `rustc --explain E0425`.
error: could not compile `my-markdown` (bin "my-markdown") due to 1 previous error
```

Have a great day!

**Comment by ChristianMurphy** [comment]
@paulfrische most likely you installed the old crate, please follow the instructions in the readme https://github.com/wooorm/markdown-rs#install

```
cargo add markdown@1.0.0-alpha.16
```

> 👉 Note: this is a new crate that reuses an old name. The old crate (`0.3.0` and lower) has a bunch of problems. Make sure to use the new crate, currently in alpha at `1.0.0-alpha.16`.

**Comment by paulfrische** [comment]
Thank you! May I open a PR with a more visible "warning" in the readme?

**Comment by ChristianMurphy** [comment]
No thanks.
There already are multiple, at the top of the readme and in the install section.
